language: node_js
services:
  - docker
node_js:
  - "4"
  - "5"
  - "6"
before_install:
  - npm config set progress false
script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
